### ISSUE TITLE
Throws unhandled exception

### ISSUE THREAD

**Issue by alr2413** [fluttercommunity/flutter_after_layout#17]
```
E/flutter (28609): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
E/flutter (28609): Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
E/flutter (28609): #0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:1088:9)
E/flutter (28609): #1      State.context (package:flutter/src/widgets/framework.dart:1094:6)
E/flutter (28609): #2      AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:31)
E/flutter (28609): #3      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (28609): #4      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (28609): #5      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
E/flutter (28609): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
E/flutter (28609): #7      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
E/flutter (28609): #8      Future._completeWithValue (dart:async/future_impl.dart:539:5)
E/flutter (28609): #9      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
E/flutter (28609): #10     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (28609): #11     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (28609): #12     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (28609): #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (28609): #14     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (28609): #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (28609): 
```

**Comment by marcglasberg** [comment]
This is solved by https://github.com/fluttercommunity/flutter_after_layout/pull/20
